### ISSUE TITLE
menu not drawing - only 1 monitor

### ISSUE THREAD

**Issue by SDE1x** [ChoZenTime/csgo-cheat-pasted-by-choZen#3]
saw the other issue, same here but only 1 monitor, tried different res, tried changing window pos, tried editing/clearing configs, etc. the "csgo-cheat" text is drawing in the top left, but pressing ins doesn't bring up a menu. Same problem as the other guy, cant interact with game as if the window is drawing.

**Comment by SDE1x** [comment]
Been three days, haven't found a solution. Can someone send me a compiled version so I know it's not my error?

**Comment by ChoZenTime** [comment]
when you saw the other issue why not read it theres a DLL  that i upload for testing without junkcode and a randoinjector
https://gofile.io/d/VPaMIC

**Comment by SDE1x** [comment]
> when you saw the other issue why not read it theres a DLL that i upload for testing without junkcode and a randoinjector
> https://gofile.io/d/VPaMIC

Tried it - sorry if I didn't mention that. I've gotten the menu to show once and I've not been able to replicate it.
